CREATE TABLE login(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(20) NOT NULL,
    CONTRASENA VARCHAR(20) NOT NULL
);

INSERT INTO login VALUES
    (NULL,'Henry','1234'),
    (NULL, 'Kenia','4321')

;

CREATE TABLE alumnos(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    SEX VARCHAR(15) NOT NULL,
    FECHA_NACIMIENTO VARCHAR(20)
);

INSERT INTO alumnos VALUES
    (NULL,'HENRY','VILLARREAL PEREZ',23,'MASCULINO','13/04/1998'),
    (NULL,'KENIA','VILLARREAL PEREZ',25,'FEMENINO','01/08/1996'),
    (NULL,'JHONNATAN','PEREZ VILLARREAL',23,'MASCULINO','13/04/2000')
;